common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 1;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\components\Breadcrumbs;
use common\components\Image;
use common\components\Notify;
use backend\controllers\BaseController;
use common\models\ProfileForm;
use common\models\User;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Site controller
 */
class SiteController extends BaseController
{

    public function beforeAction($action)
    {
        Breadcrumbs::setBread('Главная', Url::toRoute('/user/index/index'), ' <li><a href="{{link}}"><i class="fa fa-dashboard"></i> {{name}}</a></li>');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionError(){
        $this->layout = '404';

        $this->view->title = '404 - Not found';

        return $this->render('error');
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->view->title = 'Instroi - панель администратора';
        $this->layout = 'main';
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'login';
        $this->view->title = 'Instroi панель администратора';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLoginPost(){
        $login_model = new LoginForm();
        if(\Yii::$app->request->isAjax && \Yii::$app->request->isPost){
            if ($login_model->load(\Yii::$app->request->post())) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                $valid = ActiveForm::validate($login_model);
                if(!count($valid) && !\Yii::$app->request->post('ajax')){
                    //проверяем, залогинило ли пользователя
                    if($login_model->login()){
                        Notify::setMessage('success', 'Добро пожаловать на сайт!');
                        $redirect = '';
                        if(\Yii::$app->session->get('redirect')){
                            $redirect = \Yii::$app->session->get('redirect');
                        } else {
                            $redirect = Url::toRoute('/site/index');
                        }
                        $this->success([
                            'jquery' => [
                                [
                                    'action' => 'redirect',
                                    'link' => $redirect
                                ]
                            ]
                        ]);
                    }else {
                        $this->error('Вы ввели не верный логин или пароль!');
                    }
                } else {
                    return $valid;
                }
            }
        }
    }


    public function actionProfile(){
        $this->layout = 'main';

        $this->view->title = 'Личный профиль';

        Breadcrumbs::setBread('Личный профиль');

        $profileModel = new ProfileForm();

        return $this->render('profile',array(
            'user' => \Yii::$app->user->identity,
            'profile_model' => $profileModel
        ));
    }

    public function actionProfilePost(){
        $profile_form = new ProfileForm();
        if(\Yii::$app->request->isAjax && \Yii::$app->request->isPost){
            if ($profile_form->load(\Yii::$app->request->post())) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                $valid = ActiveForm::validate($profile_form);
                if(!count($valid) && !\Yii::$app->request->post('ajax')){
                    $result = $profile_form->saveData();
                    if($result) {
                        $this->success([
                            'jquery' => [
                                [
                                    'action' => 'message',
                                    'text' => 'Новые данные успешно сохранены!',
                                    'type' => 'success'
                                ],
                                [
                                    'action' => 'insertion',
                                    'selector' => '.user-name',
                                    'content' => $profile_form->name ? $profile_form->name : $profile_form->email,
                                    'method' => 'text',
                                ],
                                [
                                    'action' => 'insertion',
                                    'selector' => '.education-text',
                                    'content' => $profile_form->education ? $profile_form->education : 'Не указано',
                                    'method' => 'text',
                                ],
                                [
                                    'action' => 'insertion',
                                    'selector' => '.position-text',
                                    'content' => $profile_form->position ?  $profile_form->position : 'Программист',
                                    'method' => 'text',
                                ],
                            ]
                        ]);
                    } else {
                        $this->error('Что-то пошло не так, перезагрузите страницу и попробуйте снова!');
                    }
                } else {
                    return $valid;
                }
            }
        }
    }

    public function actionUploadPhoto(){
        if(\Yii::$app->request->isPost){
            $user_id = \Yii::$app->request->post('user_id');

            $name = Image::upload('user','image');

            if($name){
                $user = User::findOne(['id' => $user_id]);
                $user->image = $name;
                $user->save();
            }

            $this->success([
                'name' => $name,
                'jquery' => [
                    [
                        'action' => 'attributes',
                        'attribute' => 'src',
                        'selector' => '.user-avatar',
                        'value' => 'http://'.str_replace('admin.','',$_SERVER['HTTP_HOST']).Url::to('@web/media/images/user/small/'.$name),
                        'method' => 'attr'
                    ]
                ],
            ]);

        }
    }

    public function actionRemoveImage(){
        if(\Yii::$app->request->isPost){
            $file_name = \Yii::$app->request->post('name');

            $result = Image::remove('user', $file_name);

            if($result){
                $user = User::findOne(['image' => $file_name]);
                $user->image = '';
                $user->save();

                $this->success([
                    'jquery' => [
                        [
                            'action' => 'attributes',
                            'attribute' => 'src',
                            'selector' => '.user-avatar',
                            'value' => Url::to('@web/media/pic/avatar.png',true),
                            'method' => 'attr'
                        ],
                        [
                            'action' => 'message',
                            'type' => 'success',
                            'text' => 'Изображение успешно удалено!'
                        ]
                    ],
                ]);
            } else {
                $this->error('Что-то пошло не так, перезагрузите страницу!');
            }

        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

backend/views/widgets/User/Footer.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.3.5
    </div>
    <strong>Copyright &copy; 2016 <a target="_blank" href="http://wezom.com.ua">Wezom</a></strong> агенство системных интернет решений
</footer>

backend/views/widgets/User/Header.php
<header class="main-header">
    <!-- Logo -->
    <a href="<?php echo \yii\helpers\Url::home();?>" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>INS</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Instroi system</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Скрыть навигацию</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <?php echo \backend\components\Widgets::get('CallbackHeader');?>

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php if(is_file(Yii::getAlias('@frontend/web/media/images/user/small/'.Yii::$app->user->identity->image))){?>
                            <img src="<?php echo 'http://'.str_replace('admin.','',$_SERVER['HTTP_HOST']).\yii\helpers\Url::to('@web/media/images/user/small/'.Yii::$app->user->identity->image);?>" class="user-image user-avatar" alt="User Image">
                        <?php } else {?>
                            <img src="<?php echo \yii\helpers\Url::to('@web/media/pic/avatar.png');?>" class="user-image user-avatar" alt="User Image">
                        <?php }?>
                        <span class="hidden-xs user-name"><?php echo Yii::$app->user->identity->name ? Yii::$app->user->identity->name : Yii::$app->user->identity->email;?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <?php if(is_file(Yii::getAlias('@frontend/web/media/images/user/small/'.Yii::$app->user->identity->image))){?>
                                <img src="<?php echo 'http://'.str_replace('admin.','',$_SERVER['HTTP_HOST']).\yii\helpers\Url::to('@web/media/images/user/small/'.Yii::$app->user->identity->image);?>" class="img-circle user-avatar" alt="User Image">
                            <?php } else {?>
                                <img src="<?php echo \yii\helpers\Url::to('@web/media/pic/avatar.png');?>" class="img-circle user-avatar" alt="User Image">
                            <?php }?>

                            <p>
                                <span class="user-name"><?php echo Yii::$app->user->identity->name ? Yii::$app->user->identity->name : Yii::$app->user->identity->email;?></span>
                                <small class="position-text">Администратор</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!--<li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        </li>-->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="<?php echo \yii\helpers\Url::toRoute('/site/profile');?>" class="btn btn-default btn-flat">Профиль</a>
                            </div>
                            <div class="pull-right">
                                <a href="<?php echo \yii\helpers\Url::toRoute('/site/logout');?>" class="btn btn-default btn-flat">Выйти</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <!--<li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>-->
            </ul>
        </div>
    </nav>
</header>

backend/views/widgets/User/LeftMenu.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <?php if(is_file(Yii::getAlias('@frontend/web/media/images/user/small/'.Yii::$app->user->identity->image))){?>
                    <img src="<?php echo 'http://'.str_replace('admin.','',$_SERVER['HTTP_HOST']).\yii\helpers\Url::to('@web/media/images/user/small/'.Yii::$app->user->identity->image);?>" class="user-avatar img-circle" alt="User Image">
                <?php } else {?>
                    <img src="<?php echo \yii\helpers\Url::to('@web/media/pic/avatar.png');?>" class="user-avatar img-circle" alt="User Image">
                <?php }?>
            </div>
            <div class="pull-left info">
                <p class="user-name"><?php echo Yii::$app->user->identity->name ? Yii::$app->user->identity->name : Yii::$app->user->identity->email;?></p>
                <a href="<?php echo \yii\helpers\Url::toRoute('/site/profile');?>"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <!--<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>-->
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">Меню</li>
            <?php if(count($menu)){?>
                <?php echo \backend\components\Widgets::get('RecursiveMenu',
                    [
                        'menu' => $menu,
                        'count' => $count,
                        'module' => 'user',
                        'active_element' => 0
                    ]
                );?>
            <?php }?>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>