common/models/Slider.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "slider".
 *
 * @property integer $id
 * @property string $name
 * @property string $name2
 * @property string $text
 * @property string $image
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $status
 * @property integer $sort
 */
class Slider extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'slider';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text'], 'string'],
            [['created_at', 'updated_at', 'status', 'sort'], 'integer'],
            [['name', 'name2', 'image'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название - первая строка',
            'name2' => 'Название - вторая строка',
            'text' => 'Описание',
            'image' => 'Изображение',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status' => 'Опубликован?',
            'sort' => 'Sort',
        ];
    }
}

backend/controllers/AjaxController.php
<?php

namespace backend\controllers;

use backend\controllers\BaseController;
use common\components\Digest;
use common\components\Text;
use yii\data\ActiveDataProvider;
use yii\db\Query;

class AjaxController extends BaseController
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionChangeStatus(){
        if(\Yii::$app->request->isPost && \Yii::$app->request->post('id') && \Yii::$app->request->post('tableName')){
            \Yii::$app->db->createCommand()->update(
                \Yii::$app->request->post('tableName'),
                ['status' => \Yii::$app->request->post('status')],
                ['id' => \Yii::$app->request->post('id')]
            )->query();
            $this->success();
        } else {
            $this->error();
        }
    }

    public function actionChangeSort(){
        if(\Yii::$app->request->isPost && \Yii::$app->request->post('ids') && \Yii::$app->request->post('tableName')){
            if(is_array(\Yii::$app->request->post('ids'))){
                foreach (\Yii::$app->request->post('ids') as $key=>$id){
                    \Yii::$app->db->createCommand()->update(
                        \Yii::$app->request->post('tableName'),
                        ['sort' => $key],
                        ['id' => $id]
                    )->query();
                }
            }
        } else {
            $this->error();
        }
    }

    public function actionReadDigestMessage(){
        if(\Yii::$app->request->isPost && \Yii::$app->request->post('id')){
            $message_id = \Yii::$app->request->post('id');
            $message = Digest::findOne(['id' => $message_id]);
            $message->status = 1;
            $message->save();
            $count = Digest::getCountUnreadMessages(\Yii::$app->user->id);

            $this->success([
                'count' => $count
            ]);
        }
    }

    public function actionTranslit(){
        if(\Yii::$app->request->isPost && \Yii::$app->request->post('val')){
            $val = \Yii::$app->request->post('val');
            $dst = Text::translit($val);
            $this->success([
                'jquery' => [
                    [
                        'action' => 'attributes',
                        'selector' => '.translitDst',
                        'value' => $dst,
                        'attribute' => 'value',
                        'method' => 'attr',
                    ],
                ]
            ]);
        }
    }

}

backend/controllers/SliderController.php
<?php

namespace backend\controllers;

use backend\components\Breadcrumbs;
use common\components\Image;
use common\components\Notify;
use Yii;
use common\models\Slider;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * SliderController implements the CRUD actions for Slider model.
 */
class SliderController extends BaseController
{

    public function beforeAction($action)
    {
        Breadcrumbs::setBread('Главная', Url::toRoute('/admin/index/index'), ' <li><a href="{{link}}"><i class="fa fa-dashboard"></i> {{name}}</a></li>');
        Breadcrumbs::setBread('Слайдер',Url::toRoute('/slider/index'));
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Slider models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->view->title = 'Слайдер';


        $dataProvider = new ActiveDataProvider([
            'query' => Slider::find()->orderBy(['sort' => SORT_ASC]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'tableName' => Slider::tableName()
        ]);
    }

    /**
     * Displays a single Slider model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Slider model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Slider();

        $this->view->title = 'Добавить слайд';
        Breadcrumbs::setBread('Добавить слайд');

        $model->status = 1;
        return $this->render('create', [
            'model' => $model,
        ]);

    }

    /**
     * Create a new record by AJAX
     * 
     * @return mixed
     */
    public function actionCreatePost(){
        $model = new Slider();

        if(\Yii::$app->request->isAjax && \Yii::$app->request->isPost){
            if ($model->load(\Yii::$app->request->post())) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                $valid = ActiveForm::validate($model);
                if(!count($valid) && !\Yii::$app->request->post('ajax')){
                    $result = $model->save();
                    if($result){
                        Notify::setMessage('success','Данные успешно сохранены!');
                        $this->success([
                            'jquery' => [
                                [
                                    'action' => 'redirect',
                                    'link' => Url::toRoute('/slider/update?id='.$model->id)
                                ]
                            ]
                        ]);
                    } else{
                        $this->error('Что-то пошло не так, перезагрузите страницу!');
                    }
                } else {
                    return $valid;
                }
            }
        }
    }

    /**
     * Updates an existing Slider model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $this->view->title = 'Редактирование слайда: '.$model->name . ' ' . $model->name2;
        Breadcrumbs::setBread('Редактирование слайда: '.$model->name . ' ' . $model->name2);

        return $this->render('update', [
            'model' => $model,
        ]);

    }

    /**
     * Update a record
     *
     * @param $id
     * @return array
     * @throws NotFoundHttpException
     */
    public function actionUpdatePost($id){
        $model = $this->findModel($id);

        if(\Yii::$app->request->isAjax && \Yii::$app->request->isPost){
            if ($model->load(\Yii::$app->request->post())) {
                \Yii::$app->response->format = Response::FORMAT_JSON;
                $valid = ActiveForm::validate($model);
                if(!count($valid) && !\Yii::$app->request->post('ajax')){
                    $result = $model->save();
                    if($result){
                        $this->success('Данные успешно сохранены!');
                    } else{
                        $this->error('Что-то пошло не так, перезагрузите страницу!');
                    }
                } else {
                    return $valid;
                }
            }
        }
    }

    /**
     * Deletes an existing Slider model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionUploadPhoto(){
        if(\Yii::$app->request->isPost){
            $id = \Yii::$app->request->post('slider_id');

            $name = Image::upload('slider','image');

            if($name){
                $model = $this->findModel($id);
                $model->image = $name;
                $model->save();
            }

            $this->success([
                'name' => $name,
            ]);

        }
    }

    public function actionRemoveImage(){
        if(\Yii::$app->request->isPost){
            $file_name = \Yii::$app->request->post('name');

            $result = Image::remove('slider', $file_name);

            if($result){
                $model = Slider::findOne(['image' => $file_name]);
                $model->image = '';
                $model->save();

                $this->success();
            } else {
                $this->error('Что-то пошло не так, перезагрузите страницу!');
            }

        }
    }

    /**
     * Finds the Slider model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Slider the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Slider::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/slider/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Slider */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box-body">

    <?php $form = ActiveForm::begin([
        'action' => '/slider/'.($model->isNewRecord ? 'create' : 'update').'-post?id='.$model->id,
        'enableClientValidation' => false,
        'enableAjaxValidation' => true,
        'options' => [
            'class' => 'wForm',
        ]
    ]); ?>

    <?= $form->field($model, 'status')->radioList([
        0 => 'Нет',
        1 => 'Да'
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'name2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>

    <?php if(!$model->isNewRecord){?>
        <div class="form-group">
            <label for="inputSkills" class="control-label">Изображение</label>
    
    
            <?php echo \backend\components\Widgets::get('Dropzone', [
                'name' => 'image',
                'uploadUrl' => \yii\helpers\Url::to('/slider/upload-photo'),
                'maxFiles' => 1,
                'removeUrl' => \yii\helpers\Url::to('/slider/remove-image'),
                'sending' => 'function(file, xhr_o, data){
                                                       data.append("slider_id", '.$model->id.')
                                                    }',
            ]);?>
    
            <?php if(is_file(Yii::getAlias('@frontend/web/media/images/slider/big/'.$model->image))){?>
                <div class="dropzone-preview"><?php echo json_encode([
                        [
                            'name' => $model->image,
                            'size' => filesize(Yii::getAlias('@frontend/web/media/images/slider/big/'.$model->image)),
                            'path' => 'http://'.str_replace('admin.','',$_SERVER['HTTP_HOST']).Yii::getAlias('@web/media/images/slider/small/'.$model->image)
                        ]
                    ]);?>
                </div>
            <?php }?>
    
        </div>
    <?php }?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a('Закрыть', \yii\helpers\Url::toRoute('/slider/index'),['class' => 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/slider/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Sitemenu */
?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?php echo Yii::$app->view->title;?>
        </h1>
        <?php echo \backend\components\Breadcrumbs::generateBreadcrumbs(); ?>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Основные данные</h3>
                    </div>

                    <?= $this->render('_form', [
                        'model' => $model,
                    ]) ?>

                </div>
            </div>
        </div>
</div>
</section>
</div>

backend/views/slider/index.php
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?php echo Yii::$app->view->title; ?>
        </h1>
        <?php echo \backend\components\Breadcrumbs::generateBreadcrumbs(); ?>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-xs-12 ">
                        <div class="box box-primary">
                            <div class="box-header">
                                <i class="ion ion-clipboard"></i>
                                <h3 class="box-title">Список слайдов</h3>

                                <a href="<?php echo \yii\helpers\Url::toRoute('/slider/create');?>" class="btn btn-default pull-right"><i class="fa fa-plus"></i> Создать</a>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <ul class="todo-list">
                                    <?php foreach ($dataProvider->getModels() as $obj){?>
                                        <li data-id="<?php echo $obj->id;?>">
                                            <!-- drag handle -->
                                              <span class="handle">
                                                <i class="fa fa-ellipsis-v"></i>
                                                <i class="fa fa-ellipsis-v"></i>
                                              </span>
                                            <span class="text">
                                                <?php if(is_file(Yii::getAlias('@frontend/web/media/images/slider/big/'.$obj->image))){?>
                                                    <img style="width: 25%" src="<?php echo 'http://'.str_replace('admin.','',$_SERVER['HTTP_HOST']).Yii::getAlias('@web/media/images/slider/small/'.$obj->image);?>" alt="">
                                                <?php }?>
                                                <a href="<?php echo \yii\helpers\Url::to('/slider/update?id='.$obj->id);?>">
                                                    <?php echo $obj->name. ' ' . $obj->name2;?>
                                                </a>
                                            </span>
                                            <!-- General tools such as edit or delete-->
                                            <div class="tools" style="font-size: 19px">
                                                <?php echo \backend\components\Widgets::get('Status', [
                                                    'status' => $obj->status,
                                                    'id' => $obj->id
                                                ]);?>
                                                <div class="btn-group">
                                                    <a href="<?php echo \yii\helpers\Url::to('/slider/update?id='.$obj->id);?>" class="btn btn-info btn-xs">Редактировать</a>
                                                    <button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown">
                                                        <span class="caret"></span>
                                                    </button>
                                                    <ul class="dropdown-menu text-12px" role="menu">
                                                        <li><a data-pjax="0" data-method="post" data-confirm="Вы уверены?" href="<?php echo \yii\helpers\Url::to('/slider/delete?id='.$obj->id);?>">Удалить</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    <?php }?>
                                </ul>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer clearfix no-border">
                                <a href="<?php echo \yii\helpers\Url::toRoute('/slider/create');?>" class="btn btn-default pull-left"><i class="fa fa-plus"></i> Создать</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<input type="hidden" id="table-name" value="<?php echo $tableName;?>">

<script>
    $(function () {

        "use strict";

        $(".todo-list").sortable({
            placeholder: "sort-highlight",
            handle: ".handle",
            forcePlaceholderSize: true,
            zIndex: 999999,
            stop: function(event, ui){
                var ids = [];
                var i = 0;
                ui.item.closest('.todo-list').find('li').each(function () {
                    if($(this).attr('data-id')) {
                        ids[i] = $(this).attr('data-id');
                        i++;
                    }
                });

                $.ajax({
                    url: '/ajax/change-sort',
                    type: 'POST',
                    dataType: 'JSON',
                    data: {
                        ids : ids,
                        tableName: $('#table-name').val()
                    },
                    success: function(data){
                        if(!data.success){
                            generate('Что-то пошло не так, перезагрузите страницу!', 'error');
                        }
                    }
                });
            }
        });
    });
</script>

backend/views/slider/update.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Sitemenu */
?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?php echo Yii::$app->view->title;?>
        </h1>
        <?php echo \backend\components\Breadcrumbs::generateBreadcrumbs();?>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Основные данные</h3>
                    </div>

                    <?= $this->render('_form', [
                        'model' => $model,
                    ]) ?>

                </div>
            </div>
        </div>
</div>
</section>
</div>

backend/views/slider/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Slider */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Sliders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="slider-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'name2',
            'text:ntext',
            'image',
            'created_at',
            'updated_at',
            'status',
        ],
    ]) ?>

</div>